name: FunkwhaleClient
targets:
  FunkwhaleClient:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [Sources/FunkwhaleClient]
    info:
      path: ./Info.plist
      version: 1.3.4
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
