//
// ActivityRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.ActivityRequest")
public typealias ActivityRequest = FunkwhaleClientAPI.ActivityRequest

extension FunkwhaleClientAPI {

public struct ActivityRequest: Codable, JSONEncodable, Hashable {

    static let fidRule = StringRule(minLength: nil, maxLength: 500, pattern: nil)
    static let typeRule = StringRule(minLength: 1, maxLength: 100, pattern: nil)
    public var uuid: UUID?
    public var fid: String?
    public var actor: APIActorRequest
    public var payload: [String: AnyCodable]?
    public var creationDate: Date?
    public var type: String?

    public init(uuid: UUID? = nil, fid: String? = nil, actor: APIActorRequest, payload: [String: AnyCodable]? = nil, creationDate: Date? = nil, type: String? = nil) {
        self.uuid = uuid
        self.fid = fid
        self.actor = actor
        self.payload = payload
        self.creationDate = creationDate
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case fid
        case actor
        case payload
        case creationDate = "creation_date"
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(uuid, forKey: .uuid)
        try container.encodeIfPresent(fid, forKey: .fid)
        try container.encode(actor, forKey: .actor)
        try container.encodeIfPresent(payload, forKey: .payload)
        try container.encodeIfPresent(creationDate, forKey: .creationDate)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

}
