//
// ArtistAlbum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.ArtistAlbum")
public typealias ArtistAlbum = FunkwhaleClientAPI.ArtistAlbum

extension FunkwhaleClientAPI {

public struct ArtistAlbum: Codable, JSONEncodable, Hashable {

    public var tracksCount: Int
    public var cover: CoverField?
    public var isPlayable: Bool
    public var isLocal: Bool
    public var id: Int
    public var fid: String
    public var mbid: UUID
    public var title: String
    public var artist: Int
    public var releaseDate: Date
    public var creationDate: Date

    public init(tracksCount: Int, cover: CoverField?, isPlayable: Bool, isLocal: Bool, id: Int, fid: String, mbid: UUID, title: String, artist: Int, releaseDate: Date, creationDate: Date) {
        self.tracksCount = tracksCount
        self.cover = cover
        self.isPlayable = isPlayable
        self.isLocal = isLocal
        self.id = id
        self.fid = fid
        self.mbid = mbid
        self.title = title
        self.artist = artist
        self.releaseDate = releaseDate
        self.creationDate = creationDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tracksCount = "tracks_count"
        case cover
        case isPlayable = "is_playable"
        case isLocal = "is_local"
        case id
        case fid
        case mbid
        case title
        case artist
        case releaseDate = "release_date"
        case creationDate = "creation_date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tracksCount, forKey: .tracksCount)
        try container.encode(cover, forKey: .cover)
        try container.encode(isPlayable, forKey: .isPlayable)
        try container.encode(isLocal, forKey: .isLocal)
        try container.encode(id, forKey: .id)
        try container.encode(fid, forKey: .fid)
        try container.encode(mbid, forKey: .mbid)
        try container.encode(title, forKey: .title)
        try container.encode(artist, forKey: .artist)
        try container.encode(releaseDate, forKey: .releaseDate)
        try container.encode(creationDate, forKey: .creationDate)
    }
}

}
