//
// ArtistWithAlbumsInlineChannelRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.ArtistWithAlbumsInlineChannelRequest")
public typealias ArtistWithAlbumsInlineChannelRequest = FunkwhaleClientAPI.ArtistWithAlbumsInlineChannelRequest

extension FunkwhaleClientAPI {

public struct ArtistWithAlbumsInlineChannelRequest: Codable, JSONEncodable, Hashable {

    static let uuidRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var uuid: String
    public var actor: InlineActorRequest

    public init(uuid: String, actor: InlineActorRequest) {
        self.uuid = uuid
        self.actor = actor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case actor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(actor, forKey: .actor)
    }
}

}
