//
// ArtistWithAlbums.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.ArtistWithAlbums")
public typealias ArtistWithAlbums = FunkwhaleClientAPI.ArtistWithAlbums

extension FunkwhaleClientAPI {

public struct ArtistWithAlbums: Codable, JSONEncodable, Hashable {

    public var albums: [ArtistAlbum]
    public var tags: [String]
    public var attributedTo: APIActor?
    public var channel: ArtistWithAlbumsInlineChannel?
    public var tracksCount: Int
    public var id: Int
    public var fid: String
    public var mbid: UUID
    public var name: String
    public var contentCategory: String
    public var creationDate: Date
    public var isLocal: Bool
    public var cover: CoverField?

    public init(albums: [ArtistAlbum], tags: [String], attributedTo: APIActor?, channel: ArtistWithAlbumsInlineChannel?, tracksCount: Int, id: Int, fid: String, mbid: UUID, name: String, contentCategory: String, creationDate: Date, isLocal: Bool, cover: CoverField?) {
        self.albums = albums
        self.tags = tags
        self.attributedTo = attributedTo
        self.channel = channel
        self.tracksCount = tracksCount
        self.id = id
        self.fid = fid
        self.mbid = mbid
        self.name = name
        self.contentCategory = contentCategory
        self.creationDate = creationDate
        self.isLocal = isLocal
        self.cover = cover
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case albums
        case tags
        case attributedTo = "attributed_to"
        case channel
        case tracksCount = "tracks_count"
        case id
        case fid
        case mbid
        case name
        case contentCategory = "content_category"
        case creationDate = "creation_date"
        case isLocal = "is_local"
        case cover
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(albums, forKey: .albums)
        try container.encode(tags, forKey: .tags)
        try container.encode(attributedTo, forKey: .attributedTo)
        try container.encode(channel, forKey: .channel)
        try container.encode(tracksCount, forKey: .tracksCount)
        try container.encode(id, forKey: .id)
        try container.encode(fid, forKey: .fid)
        try container.encode(mbid, forKey: .mbid)
        try container.encode(name, forKey: .name)
        try container.encode(contentCategory, forKey: .contentCategory)
        try container.encode(creationDate, forKey: .creationDate)
        try container.encode(isLocal, forKey: .isLocal)
        try container.encode(cover, forKey: .cover)
    }
}

}
