//
// AttachmentRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.AttachmentRequest")
public typealias AttachmentRequest = FunkwhaleClientAPI.AttachmentRequest

extension FunkwhaleClientAPI {

public struct AttachmentRequest: Codable, JSONEncodable, Hashable {

    public var file: URL

    public init(file: URL) {
        self.file = file
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case file
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(file, forKey: .file)
    }
}

}
