//
// Channel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.Channel")
public typealias Channel = FunkwhaleClientAPI.Channel

extension FunkwhaleClientAPI {

public struct Channel: Codable, JSONEncodable, Hashable {

    public var uuid: UUID?
    public var artist: SimpleChannelArtist
    public var attributedTo: APIActor
    public var actor: APIActor
    public var creationDate: Date?
    public var metadata: [String: AnyCodable]?
    public var rssUrl: String
    public var url: String
    public var downloadsCount: Int

    public init(uuid: UUID? = nil, artist: SimpleChannelArtist, attributedTo: APIActor, actor: APIActor, creationDate: Date? = nil, metadata: [String: AnyCodable]? = nil, rssUrl: String, url: String, downloadsCount: Int) {
        self.uuid = uuid
        self.artist = artist
        self.attributedTo = attributedTo
        self.actor = actor
        self.creationDate = creationDate
        self.metadata = metadata
        self.rssUrl = rssUrl
        self.url = url
        self.downloadsCount = downloadsCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case artist
        case attributedTo = "attributed_to"
        case actor
        case creationDate = "creation_date"
        case metadata
        case rssUrl = "rss_url"
        case url
        case downloadsCount = "downloads_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(uuid, forKey: .uuid)
        try container.encode(artist, forKey: .artist)
        try container.encode(attributedTo, forKey: .attributedTo)
        try container.encode(actor, forKey: .actor)
        try container.encodeIfPresent(creationDate, forKey: .creationDate)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encode(rssUrl, forKey: .rssUrl)
        try container.encode(url, forKey: .url)
        try container.encode(downloadsCount, forKey: .downloadsCount)
    }
}

}
