//
// ContentCategoryEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.ContentCategoryEnum")
public typealias ContentCategoryEnum = FunkwhaleClientAPI.ContentCategoryEnum

extension FunkwhaleClientAPI {

public enum ContentCategoryEnum: String, Codable, CaseIterable {
    case music = "music"
    case podcast = "podcast"
    case other = "other"
}
}
