//
// ContentCategoryEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.ContentCategoryEnum")
public typealias ContentCategoryEnum = FunkwhaleClientAPI.ContentCategoryEnum

extension FunkwhaleClientAPI {

/** * &#x60;music&#x60; - music * &#x60;podcast&#x60; - podcast * &#x60;other&#x60; - other */
public enum ContentCategoryEnum: String, Codable, CaseIterable {
    case music = "music"
    case podcast = "podcast"
    case other = "other"
}
}
