//
// Content.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.Content")
public typealias Content = FunkwhaleClientAPI.Content

extension FunkwhaleClientAPI {

public struct Content: Codable, JSONEncodable, Hashable {

    static let textRule = StringRule(minLength: nil, maxLength: 5000, pattern: nil)
    public var text: String?
    public var contentType: ContentTypeEnum
    public var html: String

    public init(text: String?, contentType: ContentTypeEnum, html: String) {
        self.text = text
        self.contentType = contentType
        self.html = html
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case text
        case contentType = "content_type"
        case html
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(text, forKey: .text)
        try container.encode(contentType, forKey: .contentType)
        try container.encode(html, forKey: .html)
    }
}

}
