//
// FormatEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.FormatEnum")
public typealias FormatEnum = FunkwhaleClientAPI.FormatEnum

extension FunkwhaleClientAPI {

/** * &#x60;json&#x60; - json */
public enum FormatEnum: String, Codable, CaseIterable {
    case json = "json"
}
}
