//
// LibraryFollowRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.LibraryFollowRequest")
public typealias LibraryFollowRequest = FunkwhaleClientAPI.LibraryFollowRequest

extension FunkwhaleClientAPI {

public struct LibraryFollowRequest: Codable, JSONEncodable, Hashable {

    public var target: String

    public init(target: String) {
        self.target = target
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case target
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(target, forKey: .target)
    }
}

}
