//
// LibraryPrivacyLevelEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.LibraryPrivacyLevelEnum")
public typealias LibraryPrivacyLevelEnum = FunkwhaleClientAPI.LibraryPrivacyLevelEnum

extension FunkwhaleClientAPI {

public enum LibraryPrivacyLevelEnum: String, Codable, CaseIterable {
    case me = "me"
    case instance = "instance"
    case everyone = "everyone"
}
}
