//
// LibraryForOwner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.LibraryForOwner")
public typealias LibraryForOwner = FunkwhaleClientAPI.LibraryForOwner

extension FunkwhaleClientAPI {

public struct LibraryForOwner: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: nil, maxLength: 100, pattern: nil)
    static let descriptionRule = StringRule(minLength: nil, maxLength: 5000, pattern: nil)
    public var uuid: UUID
    public var fid: String
    public var name: String
    public var description: String?
    public var privacyLevel: LibraryPrivacyLevelEnum?
    public var uploadsCount: Int
    public var size: Int
    public var creationDate: Date
    public var actor: APIActor

    public init(uuid: UUID, fid: String, name: String, description: String? = nil, privacyLevel: LibraryPrivacyLevelEnum? = nil, uploadsCount: Int, size: Int, creationDate: Date, actor: APIActor) {
        self.uuid = uuid
        self.fid = fid
        self.name = name
        self.description = description
        self.privacyLevel = privacyLevel
        self.uploadsCount = uploadsCount
        self.size = size
        self.creationDate = creationDate
        self.actor = actor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case fid
        case name
        case description
        case privacyLevel = "privacy_level"
        case uploadsCount = "uploads_count"
        case size
        case creationDate = "creation_date"
        case actor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(fid, forKey: .fid)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(privacyLevel, forKey: .privacyLevel)
        try container.encode(uploadsCount, forKey: .uploadsCount)
        try container.encode(size, forKey: .size)
        try container.encode(creationDate, forKey: .creationDate)
        try container.encode(actor, forKey: .actor)
    }
}

}
