//
// LibraryForOwnerRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.LibraryForOwnerRequest")
public typealias LibraryForOwnerRequest = FunkwhaleClientAPI.LibraryForOwnerRequest

extension FunkwhaleClientAPI {

public struct LibraryForOwnerRequest: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: 100, pattern: nil)
    static let descriptionRule = StringRule(minLength: nil, maxLength: 5000, pattern: nil)
    public var name: String
    public var description: String?
    public var privacyLevel: LibraryPrivacyLevelEnum?

    public init(name: String, description: String? = nil, privacyLevel: LibraryPrivacyLevelEnum? = nil) {
        self.name = name
        self.description = description
        self.privacyLevel = privacyLevel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case privacyLevel = "privacy_level"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(privacyLevel, forKey: .privacyLevel)
    }
}

}
