//
// ManageUserRequestStatusEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.ManageUserRequestStatusEnum")
public typealias ManageUserRequestStatusEnum = FunkwhaleClientAPI.ManageUserRequestStatusEnum

extension FunkwhaleClientAPI {

/** * &#x60;pending&#x60; - Pending * &#x60;refused&#x60; - Refused * &#x60;approved&#x60; - Approved */
public enum ManageUserRequestStatusEnum: String, Codable, CaseIterable {
    case pending = "pending"
    case refused = "refused"
    case approved = "approved"
}
}
