//
// ManageArtistRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.ManageArtistRequest")
public typealias ManageArtistRequest = FunkwhaleClientAPI.ManageArtistRequest

extension FunkwhaleClientAPI {

public struct ManageArtistRequest: Codable, JSONEncodable, Hashable {

    static let fidRule = StringRule(minLength: 1, maxLength: 500, pattern: nil)
    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let domainRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var fid: String?
    public var mbid: UUID?
    public var name: String
    public var creationDate: Date?
    public var domain: String
    public var attributedTo: ManageBaseActorRequest
    public var cover: CoverFieldRequest?
    public var contentCategory: ContentCategoryEnum?

    public init(fid: String? = nil, mbid: UUID? = nil, name: String, creationDate: Date? = nil, domain: String, attributedTo: ManageBaseActorRequest, cover: CoverFieldRequest?, contentCategory: ContentCategoryEnum? = nil) {
        self.fid = fid
        self.mbid = mbid
        self.name = name
        self.creationDate = creationDate
        self.domain = domain
        self.attributedTo = attributedTo
        self.cover = cover
        self.contentCategory = contentCategory
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fid
        case mbid
        case name
        case creationDate = "creation_date"
        case domain
        case attributedTo = "attributed_to"
        case cover
        case contentCategory = "content_category"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fid, forKey: .fid)
        try container.encodeIfPresent(mbid, forKey: .mbid)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(creationDate, forKey: .creationDate)
        try container.encode(domain, forKey: .domain)
        try container.encode(attributedTo, forKey: .attributedTo)
        try container.encode(cover, forKey: .cover)
        try container.encodeIfPresent(contentCategory, forKey: .contentCategory)
    }
}

}
