//
// ManageTargetTypeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.ManageTargetTypeEnum")
public typealias ManageTargetTypeEnum = FunkwhaleClientAPI.ManageTargetTypeEnum

extension FunkwhaleClientAPI {

/** * &#x60;domain&#x60; - domain * &#x60;actor&#x60; - actor */
public enum ManageTargetTypeEnum: String, Codable, CaseIterable {
    case domain = "domain"
    case actor = "actor"
}
}
