//
// ManageNestedArtistRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.ManageNestedArtistRequest")
public typealias ManageNestedArtistRequest = FunkwhaleClientAPI.ManageNestedArtistRequest

extension FunkwhaleClientAPI {

public struct ManageNestedArtistRequest: Codable, JSONEncodable, Hashable {

    static let fidRule = StringRule(minLength: 1, maxLength: 500, pattern: nil)
    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let domainRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var fid: String?
    public var mbid: UUID?
    public var name: String
    public var creationDate: Date?
    public var domain: String

    public init(fid: String? = nil, mbid: UUID? = nil, name: String, creationDate: Date? = nil, domain: String) {
        self.fid = fid
        self.mbid = mbid
        self.name = name
        self.creationDate = creationDate
        self.domain = domain
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fid
        case mbid
        case name
        case creationDate = "creation_date"
        case domain
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fid, forKey: .fid)
        try container.encodeIfPresent(mbid, forKey: .mbid)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(creationDate, forKey: .creationDate)
        try container.encode(domain, forKey: .domain)
    }
}

}
