//
// ManageInstancePolicy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.ManageInstancePolicy")
public typealias ManageInstancePolicy = FunkwhaleClientAPI.ManageInstancePolicy

extension FunkwhaleClientAPI {

public struct ManageInstancePolicy: Codable, JSONEncodable, Hashable {

    static let summaryRule = StringRule(minLength: nil, maxLength: 10000, pattern: nil)
    public var id: Int
    public var uuid: UUID
    public var target: ManageTarget
    public var creationDate: Date
    public var actor: String
    public var summary: String?
    public var isActive: Bool?
    public var blockAll: Bool?
    public var silenceActivity: Bool?
    public var silenceNotifications: Bool?
    public var rejectMedia: Bool?

    public init(id: Int, uuid: UUID, target: ManageTarget, creationDate: Date, actor: String, summary: String? = nil, isActive: Bool? = nil, blockAll: Bool? = nil, silenceActivity: Bool? = nil, silenceNotifications: Bool? = nil, rejectMedia: Bool? = nil) {
        self.id = id
        self.uuid = uuid
        self.target = target
        self.creationDate = creationDate
        self.actor = actor
        self.summary = summary
        self.isActive = isActive
        self.blockAll = blockAll
        self.silenceActivity = silenceActivity
        self.silenceNotifications = silenceNotifications
        self.rejectMedia = rejectMedia
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case uuid
        case target
        case creationDate = "creation_date"
        case actor
        case summary
        case isActive = "is_active"
        case blockAll = "block_all"
        case silenceActivity = "silence_activity"
        case silenceNotifications = "silence_notifications"
        case rejectMedia = "reject_media"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(target, forKey: .target)
        try container.encode(creationDate, forKey: .creationDate)
        try container.encode(actor, forKey: .actor)
        try container.encodeIfPresent(summary, forKey: .summary)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encodeIfPresent(blockAll, forKey: .blockAll)
        try container.encodeIfPresent(silenceActivity, forKey: .silenceActivity)
        try container.encodeIfPresent(silenceNotifications, forKey: .silenceNotifications)
        try container.encodeIfPresent(rejectMedia, forKey: .rejectMedia)
    }
}

}
