//
// ManageUserRequestTypeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.ManageUserRequestTypeEnum")
public typealias ManageUserRequestTypeEnum = FunkwhaleClientAPI.ManageUserRequestTypeEnum

extension FunkwhaleClientAPI {

/** * &#x60;signup&#x60; - Sign-up */
public enum ManageUserRequestTypeEnum: String, Codable, CaseIterable {
    case signup = "signup"
}
}
