//
// ManageLibraryRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.ManageLibraryRequest")
public typealias ManageLibraryRequest = FunkwhaleClientAPI.ManageLibraryRequest

extension FunkwhaleClientAPI {

public struct ManageLibraryRequest: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: 100, pattern: nil)
    static let descriptionRule = StringRule(minLength: nil, maxLength: 5000, pattern: nil)
    static let domainRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let followersUrlRule = StringRule(minLength: 1, maxLength: 500, pattern: nil)
    public var name: String
    public var description: String?
    public var domain: String
    public var privacyLevel: LibraryPrivacyLevelEnum?
    public var followersUrl: String
    public var actor: ManageBaseActorRequest

    public init(name: String, description: String? = nil, domain: String, privacyLevel: LibraryPrivacyLevelEnum? = nil, followersUrl: String, actor: ManageBaseActorRequest) {
        self.name = name
        self.description = description
        self.domain = domain
        self.privacyLevel = privacyLevel
        self.followersUrl = followersUrl
        self.actor = actor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case domain
        case privacyLevel = "privacy_level"
        case followersUrl = "followers_url"
        case actor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(domain, forKey: .domain)
        try container.encodeIfPresent(privacyLevel, forKey: .privacyLevel)
        try container.encode(followersUrl, forKey: .followersUrl)
        try container.encode(actor, forKey: .actor)
    }
}

}
