//
// ManageNoteRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.ManageNoteRequest")
public typealias ManageNoteRequest = FunkwhaleClientAPI.ManageNoteRequest

extension FunkwhaleClientAPI {

public struct ManageNoteRequest: Codable, JSONEncodable, Hashable {

    static let summaryRule = StringRule(minLength: 1, maxLength: 50000, pattern: nil)
    public var summary: String
    public var target: [String: AnyCodable]

    public init(summary: String, target: [String: AnyCodable]) {
        self.summary = summary
        self.target = target
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case summary
        case target
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(summary, forKey: .summary)
        try container.encode(target, forKey: .target)
    }
}

}
