//
// ManageUserSimple.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.ManageUserSimple")
public typealias ManageUserSimple = FunkwhaleClientAPI.ManageUserSimple

extension FunkwhaleClientAPI {

public struct ManageUserSimple: Codable, JSONEncodable, Hashable {

    static let usernameRule = StringRule(minLength: nil, maxLength: 150, pattern: "/^[\\w.@+-]+$/")
    static let emailRule = StringRule(minLength: nil, maxLength: 254, pattern: nil)
    static let nameRule = StringRule(minLength: nil, maxLength: 255, pattern: nil)
    static let uploadQuotaRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public var id: Int
    /** Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
    public var username: String
    public var email: String?
    public var name: String?
    /** Designates whether this user should be treated as active. Unselect this instead of deleting accounts. */
    public var isActive: Bool?
    /** Designates whether the user can log into this admin site. */
    public var isStaff: Bool?
    /** Designates that this user has all permissions without explicitly assigning them. */
    public var isSuperuser: Bool?
    public var dateJoined: Date?
    public var lastActivity: Date?
    public var privacyLevel: PrivacyLevelEnum?
    public var uploadQuota: Int?

    public init(id: Int, username: String, email: String? = nil, name: String? = nil, isActive: Bool? = nil, isStaff: Bool? = nil, isSuperuser: Bool? = nil, dateJoined: Date? = nil, lastActivity: Date? = nil, privacyLevel: PrivacyLevelEnum? = nil, uploadQuota: Int? = nil) {
        self.id = id
        self.username = username
        self.email = email
        self.name = name
        self.isActive = isActive
        self.isStaff = isStaff
        self.isSuperuser = isSuperuser
        self.dateJoined = dateJoined
        self.lastActivity = lastActivity
        self.privacyLevel = privacyLevel
        self.uploadQuota = uploadQuota
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case username
        case email
        case name
        case isActive = "is_active"
        case isStaff = "is_staff"
        case isSuperuser = "is_superuser"
        case dateJoined = "date_joined"
        case lastActivity = "last_activity"
        case privacyLevel = "privacy_level"
        case uploadQuota = "upload_quota"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(username, forKey: .username)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encodeIfPresent(isStaff, forKey: .isStaff)
        try container.encodeIfPresent(isSuperuser, forKey: .isSuperuser)
        try container.encodeIfPresent(dateJoined, forKey: .dateJoined)
        try container.encodeIfPresent(lastActivity, forKey: .lastActivity)
        try container.encodeIfPresent(privacyLevel, forKey: .privacyLevel)
        try container.encodeIfPresent(uploadQuota, forKey: .uploadQuota)
    }
}

}
