//
// ManageBaseActor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.ManageBaseActor")
public typealias ManageBaseActor = FunkwhaleClientAPI.ManageBaseActor

extension FunkwhaleClientAPI {

public struct ManageBaseActor: Codable, JSONEncodable, Hashable {

    static let urlRule = StringRule(minLength: nil, maxLength: 500, pattern: nil)
    static let fidRule = StringRule(minLength: nil, maxLength: 500, pattern: nil)
    static let preferredUsernameRule = StringRule(minLength: nil, maxLength: 200, pattern: nil)
    static let nameRule = StringRule(minLength: nil, maxLength: 200, pattern: nil)
    static let summaryRule = StringRule(minLength: nil, maxLength: 500, pattern: nil)
    static let inboxUrlRule = StringRule(minLength: nil, maxLength: 500, pattern: nil)
    static let outboxUrlRule = StringRule(minLength: nil, maxLength: 500, pattern: nil)
    static let sharedInboxUrlRule = StringRule(minLength: nil, maxLength: 500, pattern: nil)
    public var id: Int
    public var url: String?
    public var fid: String
    public var preferredUsername: String?
    public var fullUsername: String
    public var domain: String
    public var name: String?
    public var summary: String?
    public var type: FederationChoiceEnum?
    public var creationDate: Date
    public var lastFetchDate: Date?
    public var inboxUrl: String?
    public var outboxUrl: String?
    public var sharedInboxUrl: String?
    public var manuallyApprovesFollowers: Bool?
    public var isLocal: Bool

    public init(id: Int, url: String? = nil, fid: String, preferredUsername: String?, fullUsername: String, domain: String, name: String? = nil, summary: String? = nil, type: FederationChoiceEnum? = nil, creationDate: Date, lastFetchDate: Date? = nil, inboxUrl: String? = nil, outboxUrl: String? = nil, sharedInboxUrl: String? = nil, manuallyApprovesFollowers: Bool? = nil, isLocal: Bool) {
        self.id = id
        self.url = url
        self.fid = fid
        self.preferredUsername = preferredUsername
        self.fullUsername = fullUsername
        self.domain = domain
        self.name = name
        self.summary = summary
        self.type = type
        self.creationDate = creationDate
        self.lastFetchDate = lastFetchDate
        self.inboxUrl = inboxUrl
        self.outboxUrl = outboxUrl
        self.sharedInboxUrl = sharedInboxUrl
        self.manuallyApprovesFollowers = manuallyApprovesFollowers
        self.isLocal = isLocal
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case url
        case fid
        case preferredUsername = "preferred_username"
        case fullUsername = "full_username"
        case domain
        case name
        case summary
        case type
        case creationDate = "creation_date"
        case lastFetchDate = "last_fetch_date"
        case inboxUrl = "inbox_url"
        case outboxUrl = "outbox_url"
        case sharedInboxUrl = "shared_inbox_url"
        case manuallyApprovesFollowers = "manually_approves_followers"
        case isLocal = "is_local"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encode(fid, forKey: .fid)
        try container.encode(preferredUsername, forKey: .preferredUsername)
        try container.encode(fullUsername, forKey: .fullUsername)
        try container.encode(domain, forKey: .domain)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(summary, forKey: .summary)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encode(creationDate, forKey: .creationDate)
        try container.encodeIfPresent(lastFetchDate, forKey: .lastFetchDate)
        try container.encodeIfPresent(inboxUrl, forKey: .inboxUrl)
        try container.encodeIfPresent(outboxUrl, forKey: .outboxUrl)
        try container.encodeIfPresent(sharedInboxUrl, forKey: .sharedInboxUrl)
        try container.encodeIfPresent(manuallyApprovesFollowers, forKey: .manuallyApprovesFollowers)
        try container.encode(isLocal, forKey: .isLocal)
    }
}

}
