//
// Metadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.Metadata")
public typealias Metadata = FunkwhaleClientAPI.Metadata

extension FunkwhaleClientAPI {

public struct Metadata: Codable, JSONEncodable, Hashable {

    public var actorId: String
    public var _private: Bool
    public var shortDescription: String
    public var longDescription: String
    public var rules: String
    public var contactEmail: String
    public var terms: String
    public var nodeName: String
    public var banner: String
    public var defaultUploadQuota: Int
    public var library: NodeInfoLibrary
    public var supportedUploadExtensions: [String]
    public var allowList: AllowListStat
    public var reportTypes: [ReportType]
    public var funkwhaleSupportMessageEnabled: Bool
    public var instanceSupportMessage: String
    public var endpoints: Endpoints
    public var usage: MetadataUsage?

    public init(actorId: String, _private: Bool, shortDescription: String, longDescription: String, rules: String, contactEmail: String, terms: String, nodeName: String, banner: String, defaultUploadQuota: Int, library: NodeInfoLibrary, supportedUploadExtensions: [String], allowList: AllowListStat, reportTypes: [ReportType], funkwhaleSupportMessageEnabled: Bool, instanceSupportMessage: String, endpoints: Endpoints, usage: MetadataUsage? = nil) {
        self.actorId = actorId
        self._private = _private
        self.shortDescription = shortDescription
        self.longDescription = longDescription
        self.rules = rules
        self.contactEmail = contactEmail
        self.terms = terms
        self.nodeName = nodeName
        self.banner = banner
        self.defaultUploadQuota = defaultUploadQuota
        self.library = library
        self.supportedUploadExtensions = supportedUploadExtensions
        self.allowList = allowList
        self.reportTypes = reportTypes
        self.funkwhaleSupportMessageEnabled = funkwhaleSupportMessageEnabled
        self.instanceSupportMessage = instanceSupportMessage
        self.endpoints = endpoints
        self.usage = usage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case actorId
        case _private = "private"
        case shortDescription
        case longDescription
        case rules
        case contactEmail
        case terms
        case nodeName
        case banner
        case defaultUploadQuota
        case library
        case supportedUploadExtensions
        case allowList
        case reportTypes
        case funkwhaleSupportMessageEnabled
        case instanceSupportMessage
        case endpoints
        case usage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(actorId, forKey: .actorId)
        try container.encode(_private, forKey: ._private)
        try container.encode(shortDescription, forKey: .shortDescription)
        try container.encode(longDescription, forKey: .longDescription)
        try container.encode(rules, forKey: .rules)
        try container.encode(contactEmail, forKey: .contactEmail)
        try container.encode(terms, forKey: .terms)
        try container.encode(nodeName, forKey: .nodeName)
        try container.encode(banner, forKey: .banner)
        try container.encode(defaultUploadQuota, forKey: .defaultUploadQuota)
        try container.encode(library, forKey: .library)
        try container.encode(supportedUploadExtensions, forKey: .supportedUploadExtensions)
        try container.encode(allowList, forKey: .allowList)
        try container.encode(reportTypes, forKey: .reportTypes)
        try container.encode(funkwhaleSupportMessageEnabled, forKey: .funkwhaleSupportMessageEnabled)
        try container.encode(instanceSupportMessage, forKey: .instanceSupportMessage)
        try container.encode(endpoints, forKey: .endpoints)
        try container.encodeIfPresent(usage, forKey: .usage)
    }
}

}
