//
// MetadataUsageFavorite.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.MetadataUsageFavorite")
public typealias MetadataUsageFavorite = FunkwhaleClientAPI.MetadataUsageFavorite

extension FunkwhaleClientAPI {

public struct MetadataUsageFavorite: Codable, JSONEncodable, Hashable {

    public var tracks: TotalCount

    public init(tracks: TotalCount) {
        self.tracks = tracks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tracks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tracks, forKey: .tracks)
    }
}

}
