//
// NodeInfoLibraryMusic.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.NodeInfoLibraryMusic")
public typealias NodeInfoLibraryMusic = FunkwhaleClientAPI.NodeInfoLibraryMusic

extension FunkwhaleClientAPI {

public struct NodeInfoLibraryMusic: Codable, JSONEncodable, Hashable {

    public var hours: Int

    public init(hours: Int) {
        self.hours = hours
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hours
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(hours, forKey: .hours)
    }
}

}
