//
// PlaylistTrack.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.PlaylistTrack")
public typealias PlaylistTrack = FunkwhaleClientAPI.PlaylistTrack

extension FunkwhaleClientAPI {

public struct PlaylistTrack: Codable, JSONEncodable, Hashable {

    static let indexRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public var track: String
    public var index: Int?
    public var creationDate: Date?

    public init(track: String, index: Int? = nil, creationDate: Date? = nil) {
        self.track = track
        self.index = index
        self.creationDate = creationDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case track
        case index
        case creationDate = "creation_date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(track, forKey: .track)
        try container.encodeIfPresent(index, forKey: .index)
        try container.encodeIfPresent(creationDate, forKey: .creationDate)
    }
}

}
