//
// PlaylistAddManyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.PlaylistAddManyRequest")
public typealias PlaylistAddManyRequest = FunkwhaleClientAPI.PlaylistAddManyRequest

extension FunkwhaleClientAPI {

public struct PlaylistAddManyRequest: Codable, JSONEncodable, Hashable {

    public var tracks: [Int]
    public var allowDuplicates: Bool?

    public init(tracks: [Int], allowDuplicates: Bool? = nil) {
        self.tracks = tracks
        self.allowDuplicates = allowDuplicates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tracks
        case allowDuplicates = "allow_duplicates"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tracks, forKey: .tracks)
        try container.encodeIfPresent(allowDuplicates, forKey: .allowDuplicates)
    }
}

}
