//
// PrivacyLevelEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.PrivacyLevelEnum")
public typealias PrivacyLevelEnum = FunkwhaleClientAPI.PrivacyLevelEnum

extension FunkwhaleClientAPI {

/** * &#x60;me&#x60; - Only me * &#x60;followers&#x60; - Me and my followers * &#x60;instance&#x60; - Everyone on my instance, and my followers * &#x60;everyone&#x60; - Everyone, including people on other instances */
public enum PrivacyLevelEnum: String, Codable, CaseIterable {
    case me = "me"
    case followers = "followers"
    case instance = "instance"
    case everyone = "everyone"
}
}
