//
// RadioSessionTrackSerializerCreateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.RadioSessionTrackSerializerCreateRequest")
public typealias RadioSessionTrackSerializerCreateRequest = FunkwhaleClientAPI.RadioSessionTrackSerializerCreateRequest

extension FunkwhaleClientAPI {

public struct RadioSessionTrackSerializerCreateRequest: Codable, JSONEncodable, Hashable {

    public var session: Int

    public init(session: Int) {
        self.session = session
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case session
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(session, forKey: .session)
    }
}

}
