//
// ReportTypeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.ReportTypeEnum")
public typealias ReportTypeEnum = FunkwhaleClientAPI.ReportTypeEnum

extension FunkwhaleClientAPI {

/** * &#x60;takedown_request&#x60; - Takedown request * &#x60;invalid_metadata&#x60; - Invalid metadata * &#x60;illegal_content&#x60; - Illegal content * &#x60;offensive_content&#x60; - Offensive content * &#x60;other&#x60; - Other */
public enum ReportTypeEnum: String, Codable, CaseIterable {
    case takedownRequest = "takedown_request"
    case invalidMetadata = "invalid_metadata"
    case illegalContent = "illegal_content"
    case offensiveContent = "offensive_content"
    case other = "other"
}
}
