//
// ReportTypeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.ReportTypeEnum")
public typealias ReportTypeEnum = FunkwhaleClientAPI.ReportTypeEnum

extension FunkwhaleClientAPI {

public enum ReportTypeEnum: String, Codable, CaseIterable {
    case takedownRequest = "takedown_request"
    case invalidMetadata = "invalid_metadata"
    case illegalContent = "illegal_content"
    case offensiveContent = "offensive_content"
    case other = "other"
}
}
