//
// SpaManifestRelatedApplications.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.SpaManifestRelatedApplications")
public typealias SpaManifestRelatedApplications = FunkwhaleClientAPI.SpaManifestRelatedApplications

extension FunkwhaleClientAPI {

public struct SpaManifestRelatedApplications: Codable, JSONEncodable, Hashable {

    public var platform: String
    public var url: String
    public var id: String

    public init(platform: String, url: String, id: String) {
        self.platform = platform
        self.url = url
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case platform
        case url
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(platform, forKey: .platform)
        try container.encode(url, forKey: .url)
        try container.encode(id, forKey: .id)
    }
}

}
