//
// TextPreviewRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.TextPreviewRequest")
public typealias TextPreviewRequest = FunkwhaleClientAPI.TextPreviewRequest

extension FunkwhaleClientAPI {

public struct TextPreviewRequest: Codable, JSONEncodable, Hashable {

    static let textRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var text: String

    public init(text: String) {
        self.text = text
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case text
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(text, forKey: .text)
    }
}

}
