//
// TextPreview.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.TextPreview")
public typealias TextPreview = FunkwhaleClientAPI.TextPreview

extension FunkwhaleClientAPI {

public struct TextPreview: Codable, JSONEncodable, Hashable {

    public var rendered: String

    public init(rendered: String) {
        self.rendered = rendered
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rendered
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rendered, forKey: .rendered)
    }
}

}
