//
// TotalCount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.TotalCount")
public typealias TotalCount = FunkwhaleClientAPI.TotalCount

extension FunkwhaleClientAPI {

public struct TotalCount: Codable, JSONEncodable, Hashable {

    public var total: Int

    public init(total: Int) {
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(total, forKey: .total)
    }
}

}
