//
// Track.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.Track")
public typealias Track = FunkwhaleClientAPI.Track

extension FunkwhaleClientAPI {

public struct Track: Codable, JSONEncodable, Hashable {

    public var artist: SimpleArtist
    public var album: TrackAlbum
    public var uploads: [AnyCodable]
    public var listenUrl: String
    public var tags: [String]
    public var attributedTo: APIActor?
    public var id: Int
    public var fid: String
    public var mbid: UUID
    public var title: String
    public var creationDate: Date
    public var isLocal: Bool
    public var position: Int
    public var discNumber: Int
    public var downloadsCount: Int
    public var copyright: String
    public var license: String
    public var cover: CoverField?
    public var isPlayable: Bool

    public init(artist: SimpleArtist, album: TrackAlbum, uploads: [AnyCodable], listenUrl: String, tags: [String], attributedTo: APIActor?, id: Int, fid: String, mbid: UUID, title: String, creationDate: Date, isLocal: Bool, position: Int, discNumber: Int, downloadsCount: Int, copyright: String, license: String, cover: CoverField?, isPlayable: Bool) {
        self.artist = artist
        self.album = album
        self.uploads = uploads
        self.listenUrl = listenUrl
        self.tags = tags
        self.attributedTo = attributedTo
        self.id = id
        self.fid = fid
        self.mbid = mbid
        self.title = title
        self.creationDate = creationDate
        self.isLocal = isLocal
        self.position = position
        self.discNumber = discNumber
        self.downloadsCount = downloadsCount
        self.copyright = copyright
        self.license = license
        self.cover = cover
        self.isPlayable = isPlayable
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case artist
        case album
        case uploads
        case listenUrl = "listen_url"
        case tags
        case attributedTo = "attributed_to"
        case id
        case fid
        case mbid
        case title
        case creationDate = "creation_date"
        case isLocal = "is_local"
        case position
        case discNumber = "disc_number"
        case downloadsCount = "downloads_count"
        case copyright
        case license
        case cover
        case isPlayable = "is_playable"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(artist, forKey: .artist)
        try container.encode(album, forKey: .album)
        try container.encode(uploads, forKey: .uploads)
        try container.encode(listenUrl, forKey: .listenUrl)
        try container.encode(tags, forKey: .tags)
        try container.encode(attributedTo, forKey: .attributedTo)
        try container.encode(id, forKey: .id)
        try container.encode(fid, forKey: .fid)
        try container.encode(mbid, forKey: .mbid)
        try container.encode(title, forKey: .title)
        try container.encode(creationDate, forKey: .creationDate)
        try container.encode(isLocal, forKey: .isLocal)
        try container.encode(position, forKey: .position)
        try container.encode(discNumber, forKey: .discNumber)
        try container.encode(downloadsCount, forKey: .downloadsCount)
        try container.encode(copyright, forKey: .copyright)
        try container.encode(license, forKey: .license)
        try container.encode(cover, forKey: .cover)
        try container.encode(isPlayable, forKey: .isPlayable)
    }
}

}
