//
// Usage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.Usage")
public typealias Usage = FunkwhaleClientAPI.Usage

extension FunkwhaleClientAPI {

public struct Usage: Codable, JSONEncodable, Hashable {

    public var users: UsersUsage

    public init(users: UsersUsage) {
        self.users = users
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case users
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(users, forKey: .users)
    }
}

}
