//
// UsersUsage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.UsersUsage")
public typealias UsersUsage = FunkwhaleClientAPI.UsersUsage

extension FunkwhaleClientAPI {

public struct UsersUsage: Codable, JSONEncodable, Hashable {

    public var total: Int
    public var activeHalfyear: Int
    public var activeMonth: Int

    public init(total: Int, activeHalfyear: Int, activeMonth: Int) {
        self.total = total
        self.activeHalfyear = activeHalfyear
        self.activeMonth = activeMonth
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case activeHalfyear
        case activeMonth
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(total, forKey: .total)
        try container.encode(activeHalfyear, forKey: .activeHalfyear)
        try container.encode(activeMonth, forKey: .activeMonth)
    }
}

}
