//
// UserDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.UserDetails")
public typealias UserDetails = FunkwhaleClientAPI.UserDetails

extension FunkwhaleClientAPI {

/** User model w/o password */
public struct UserDetails: Codable, JSONEncodable, Hashable {

    static let usernameRule = StringRule(minLength: nil, maxLength: 150, pattern: "/^[\\w.@+-]+$/")
    static let firstNameRule = StringRule(minLength: nil, maxLength: 150, pattern: nil)
    static let lastNameRule = StringRule(minLength: nil, maxLength: 150, pattern: nil)
    public var pk: Int
    /** Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
    public var username: String
    public var email: String
    public var firstName: String?
    public var lastName: String?

    public init(pk: Int, username: String, email: String, firstName: String? = nil, lastName: String? = nil) {
        self.pk = pk
        self.username = username
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pk
        case username
        case email
        case firstName = "first_name"
        case lastName = "last_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pk, forKey: .pk)
        try container.encode(username, forKey: .username)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
    }
}

}
