//
// UserFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "FunkwhaleClientAPI.UserFilter")
public typealias UserFilter = FunkwhaleClientAPI.UserFilter

extension FunkwhaleClientAPI {

public struct UserFilter: Codable, JSONEncodable, Hashable {

    public var uuid: UUID
    public var target: ModerationTarget
    public var creationDate: Date

    public init(uuid: UUID, target: ModerationTarget, creationDate: Date) {
        self.uuid = uuid
        self.target = target
        self.creationDate = creationDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case target
        case creationDate = "creation_date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(uuid, forKey: .uuid)
        try container.encode(target, forKey: .target)
        try container.encode(creationDate, forKey: .creationDate)
    }
}

}
